import React from 'react';
import { FileText, ArrowLeft, AlertTriangle, CheckCircle2, Clock, Scale } from 'lucide-react';
import { motion } from 'motion/react';
import { GlassCard } from './GlassCard';

interface TermsPageProps {
  onBack: () => void;
}

export const TermsPage: React.FC<TermsPageProps> = ({ onBack }) => {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-8">
      
      {/* Top Breadcrumb / Back Action */}
      <motion.div
        initial={{ opacity: 0, y: 10 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.3 }}
        className="flex items-center justify-between"
      >
        <button
          onClick={onBack}
          className="inline-flex items-center gap-1.5 text-xs font-mono text-slate-600 hover:text-slate-900 transition-colors cursor-pointer"
        >
          <ArrowLeft className="w-3.5 h-3.5" />
          <span>Back to Hub</span>
        </button>

        <div className="flex items-center gap-1.5 text-[11px] font-mono text-slate-400">
          <Clock className="w-3 h-3 text-slate-400" />
          <span>Last Revised: September 2026</span>
        </div>
      </motion.div>

      {/* Main Glass Document Container */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5, ease: 'easeOut' }}
      >
        <GlassCard className="p-8 sm:p-12 border border-slate-200/80 bg-white/80 shadow-lg relative">
          
          {/* Header Banner */}
          <div className="pb-8 border-b border-slate-200/80 mb-8">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full text-xs font-semibold bg-emerald-50 text-emerald-800 border border-emerald-300 font-mono shadow-xs mb-3">
              <Scale className="w-3.5 h-3.5 text-emerald-600" />
              <span>Institutional Service Agreement</span>
            </div>
            <h1 className="text-2xl sm:text-4xl font-extrabold text-slate-900 tracking-tight">
              Terms of Service & Usage Agreement
            </h1>
            <p className="text-xs sm:text-sm text-slate-500 font-mono mt-1">
              Verifyn Corporate Intelligence Platform • Please read carefully before using the software
            </p>
          </div>

          {/* Statutory Financial Disclaimer Box */}
          <div className="p-4 rounded-2xl bg-amber-50 border border-amber-300 text-amber-950 text-xs font-sans mb-8 flex items-start gap-3">
            <AlertTriangle className="w-5 h-5 text-amber-600 shrink-0 mt-0.5" />
            <div className="space-y-1">
              <strong className="font-mono text-amber-900 uppercase tracking-wider block">
                Statutory Financial Disclaimer (Not Investment Advice)
              </strong>
              <p className="leading-relaxed">
                Verifyn provides informational tools aggregating publicly filed data (SEC EDGAR, USPTO PatentsView, and Companies House). Verifyn is not a registered investment adviser, broker-dealer, or financial advisory firm. No content, risk score, or automated forensic summary generated by this platform constitutes a recommendation to buy, sell, or hold securities. All investing carries risk of permanent loss.
              </p>
            </div>
          </div>

          {/* Content Document */}
          <div className="prose prose-slate max-w-none text-xs sm:text-sm leading-relaxed text-slate-700 space-y-6">
            
            <section className="space-y-2">
              <h2 className="text-base font-bold text-slate-900 font-mono uppercase tracking-wider flex items-center gap-2">
                <span className="w-2 h-2 rounded-full bg-emerald-500"></span>
                1. Acceptance of Terms
              </h2>
              <p>
                By accessing or using the Verifyn web application, API, or intelligence services (&quot;Service&quot;), you agree to be bound by these Terms of Service. If you are entering into this agreement on behalf of a company or legal entity, you represent that you possess the authority to bind such entity.
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="text-base font-bold text-slate-900 font-mono uppercase tracking-wider flex items-center gap-2">
                <span className="w-2 h-2 rounded-full bg-emerald-500"></span>
                2. Permitted Use & Usage Quotas
              </h2>
              <p>
                Verifyn grants you a non-exclusive, non-transferable, revocable license to access corporate filings, patent registries, and AI summaries in accordance with your subscription tier:
              </p>
              <ul className="list-disc pl-5 space-y-1 text-slate-600">
                <li>
                  <strong>Free Explorer Tier:</strong> Capped at 3 entity searches per browser session, subject to IP rate limiting.
                </li>
                <li>
                  <strong>Verifyn Pro Tier ($9.99/mo):</strong> Grants unlimited corporate searches, unredacted Cap Table & 13F ownership analyses, Gemini AI 10-K forensic risk scores, and PDF exports.
                </li>
                <li>
                  <strong>Abuse & Automated Scraping:</strong> Users may not subject the platform to high-volume distributed scraping or automated denial-of-service attempts. Automated queries exceeding reasonable analyst workflow will result in immediate API throttling.
                </li>
              </ul>
            </section>

            <section className="space-y-2">
              <h2 className="text-base font-bold text-slate-900 font-mono uppercase tracking-wider flex items-center gap-2">
                <span className="w-2 h-2 rounded-full bg-emerald-500"></span>
                3. Subscriptions, Billing & Cancellations
              </h2>
              <p>
                All billing operations are administered by Lemon Squeezy Inc., acting as the authorized Merchant of Record:
              </p>
              <ul className="list-disc pl-5 space-y-1 text-slate-600">
                <li>
                  <strong>Billing Cycle:</strong> Subscriptions renew automatically on a recurring monthly or annual basis until cancelled by the subscriber.
                </li>
                <li>
                  <strong>Instant Cancellation:</strong> You may cancel your subscription at any time via the Lemon Squeezy customer portal. Access remains active through the end of the current billing cycle.
                </li>
                <li>
                  <strong>Refunds:</strong> We provide a full 14-day no-questions-asked refund window for any initial subscription payment upon request through our Contact Desk.
                </li>
              </ul>
            </section>

            <section className="space-y-2">
              <h2 className="text-base font-bold text-slate-900 font-mono uppercase tracking-wider flex items-center gap-2">
                <span className="w-2 h-2 rounded-full bg-emerald-500"></span>
                4. Data Accuracy & Third-Party Registries
              </h2>
              <p>
                While Verifyn aggregates data directly from certified government repositories (SEC EDGAR, USPTO, and UK Companies House), we make no warranties regarding the timeliness, completeness, or absolute precision of corporate disclosures. Corporate issuers bear sole responsibility for the veracity of their statutory filings.
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="text-base font-bold text-slate-900 font-mono uppercase tracking-wider flex items-center gap-2">
                <span className="w-2 h-2 rounded-full bg-emerald-500"></span>
                5. Turnkey Asset & Commercial Transferability (Acquire.com)
              </h2>
              <p>
                The Verifyn architecture is licensed under commercial turnkey terms. When transferred or acquired through verified business marketplaces such as Acquire.com, the buyer receives complete, unencumbered rights to the source repository, documentation, deployment scripts, and intellectual property without ongoing royalty claims.
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="text-base font-bold text-slate-900 font-mono uppercase tracking-wider flex items-center gap-2">
                <span className="w-2 h-2 rounded-full bg-emerald-500"></span>
                6. Limitation of Liability
              </h2>
              <p>
                To the maximum extent permitted by applicable law, in no event shall Verifyn, its creators, or successors be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, investment losses, or data corruption arising from the use or inability to use the platform.
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="text-base font-bold text-slate-900 font-mono uppercase tracking-wider flex items-center gap-2">
                <span className="w-2 h-2 rounded-full bg-emerald-500"></span>
                7. Contact & Legal Notices
              </h2>
              <p>
                Formal legal notices or queries regarding these Terms may be directed to:
              </p>
              <div className="p-3 rounded-xl bg-slate-100/80 border border-slate-200 font-mono text-xs text-slate-800">
                Verifyn Legal Desk<br />
                Email: legal@verifyn-intel.io<br />
                Resolution Desk: /contact
              </div>
            </section>

          </div>

          {/* Footer Affirmation */}
          <div className="mt-8 pt-6 border-t border-slate-200 flex items-center justify-between text-xs text-slate-500 font-mono">
            <div className="flex items-center gap-2">
              <CheckCircle2 className="w-4 h-4 text-emerald-600" />
              <span>Legally Binding Agreement</span>
            </div>
            <button
              onClick={onBack}
              className="text-emerald-700 hover:text-emerald-800 font-bold underline cursor-pointer"
            >
              Return to Platform →
            </button>
          </div>

        </GlassCard>
      </motion.div>

    </div>
  );
};
